#ifndef __DATA_TRANSFER_H__
#define __DATA_TRANSFER_H__

typedef enum 
{
	SRV_CL_SEND_FILE_DATA = 0,
	SRV_CL_SEND_FILE_EXIST,
	SRV_CL_SEND_FILE_NOT_EXIST,
	SRV_CL_SEND_FILE_END,
	SRV_CL_SEND_FILE_LIST,
	CL_SRV_REQUEST_SEND_FILE,
	CL_SRV_REQUEST_FILE_LIST,
}REQUEST_TYPE_ENUM;

typedef struct
{
	REQUEST_TYPE_ENUM request;
	char data[1024]; 
}TRANFER_MESSAGE_ST;

#endif